name: A basic workflow 
on :
  workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value1
jobs:
    mainjob:
      runs-on: ubuntu-latest

      env:
        greeting: Dear
        testvar: value2

      steps:
        - name: print value of env var
          run: |
            echo: "$DAY_OF_WEEK is gr8 day"
            echo: ${{env.testvar}}
          env:
              testvar: value3